### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by norifumi0129** [norifumi0129/furima-40023#20]
# URL
https://furima-40023.onrender.com

# Basic認証のIDとパスワード
## ID
admin
## password
2222
 	
### mail address
1192@test.com
### password
1192kamakura

### mail address
1118@test.com
### password
1181heike

**Comment by snkw-works** [comment]
@norifumi0129 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **商品出品ページにて、入力された販売価格によって、販売手数料や販売利益が変わるよう修正しましょう(JavaScriptを使用して実装すること)**
販売価格を入力しても、販売手数料や販売利益が表示されない状態です。

- [x] **ログイン状態の場合は、自身が出品した販売中商品の商品情報編集ページに遷移できるよう修正しましょう**
「商品の編集」ボタンをクリックしても、編集ページに遷移できない状態です。

- [x] **商品購入ページにて、クレジットカードの情報が入力できるよう修正しましょう**
現在、クレジットカードの情報入力欄は表示されていますが、カーソルを合わせても入力ができない状態です。

※上記により、編集機能と購入機能に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by motomuun** [comment]
@norifumi0129 さん、再度ご提出頂きありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x]  **商品出品ページにて、入力された販売価格によって、販売手数料や販売利益が変わるよう修正しましょう(JavaScriptを使用して実装すること)**
エラーハンドリングによって出品ページに戻った後、販売手数料や販売利益が表示されなくなります。いつでも表示されるように修正をお願いします。

- [x] **クレジットカード情報は必須であり、下記PAY.JPテストカードの情報で決済ができること**
```
【カード情報】
・カード番号：4242424242424242
・有効期限：今日より未来の日付(実際に入力したのは3/33です)
・セキュリティコード：123
```
上記を入力しても「Token can't be blank」というエラーメッセージが表示され、決済が完了出来ません。決済できるように修正をお願いします。

※上記により、購入機能に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by motomuun** [comment]
@norifumi0129 さん、再度ご提出頂きありがとうございます‼︎
前回依頼した箇所に関しては、修正が完了しておりました。素晴らしいです。
前回動作確認が出来なかった、売却済み商品に関して、一点修正していただきたい箇所がございます。
まもなくフリマアプリも完成です！以下のご確認をお願いします。

[修正依頼箇所]
**商品編集機能の確認**
- [x] **ログイン状態の場合でも、自身が出品した売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移すること**
自身が出品した売却済み商品の商品情報編集ページへ遷移できてしまいます。遷移できず、トップページへ遷移するように修正をお願いします。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by snkw-works** [comment]
@norifumi0129 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、前回お伝えした点については修正が確認できました。ありがとうございます。
引き続き、修正していただきたい箇所がございましたので、以下のご確認をお願いします！

[修正依頼箇所]
- [x] **ログイン状態の場合は、自身が出品した販売中商品の商品情報編集ページに遷移できるよう修正しましょう**
「商品の編集」ボタンをクリックしても、編集ページに遷移できない状態です。販売中の商品であれば編集ページに遷移できるように修正しましょう。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by snkw-works** [comment]
@norifumi0129 さん、修正とご提出ありがとうございます‼︎
正常に動作することが確認できました！ **LGTM** です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
